### ISSUE TITLE
Can't install due to self-signed certificates on ubuntu 14.04

### ISSUE THREAD

**Issue by mbroadst** [kylef/swiftenv#149]
Is it possible to provide some way to pass `--insecure` to the curl call? 

```
+ swiftenv install 4.2
Downloading https://swift.org/builds/swift-4.2-release/ubuntu1404/swift-4.2-RELEASE/swift-4.2-RELEASE-ubuntu14.04.tar.gz
/tmp/swiftenv-4.2-ubuntu ~/mongo-swift-driver
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by kylef** [comment]
Not easily, you could modify the source (libexec/swiftenv-install) and add the --insecure line to curl. I am not sure that I would encourage doing so by making it easier and instead encourage users to solve problems with their CA bundles.

I think the problem is perhaps missing or mis-configured CA certificates on Ubuntu 14.04 as it appears that the swift.org certificate chain is valid. It could also just be a man-in-the middle, with a malicious actor playing swift.org which is why I would discourage blindly downloading swift binaries from untrusted sources. You will likely be running `swift` from this tarball, and if the tarball is comprimised you can be executing malicious software. These risks could be mitigated by using the `--verify` option which requires GPG and Swift public keys to be added to the public keychain (https://swiftenv.fuller.li/en/latest/commands.html#verifying-linux-binary-packages):

> When downloading a pre-built binary package, swiftenv can also download the corresponding signature and verify it with gpg. This option assumes gpg is installed on the system, and the [Swift public keys](https://swift.org/download/#active-signing-keys) already exist on the public gpg keyring. If verification fails, the version will not be installed. Signatures are currently only checked in this way for Linux builds.
>
> https://swift.org/download/#active-signing-keys

**Comment by mbroadst** [comment]
Thanks for the quick response. I verified the cert chain is valid, so this must be an issue with ubuntu 14.04, closing.
