### ISSUE TITLE
swiftenv makes Go build tools inoperable

### ISSUE THREAD

**Issue by cohix** [kylef/swiftenv#181]
I've been working on some things with SwiftWasm and Go, and I came across something strange.

If you have the following in your zsh_profile:
```bash
export SWIFTENV_ROOT="$HOME/.swiftenv"
export PATH="$SWIFTENV_ROOT/bin:$PATH"
eval "$(swiftenv init -)"
```
as described by the install steps (Mac, installed via Homebrew), then building anything with Go that involves CGO will hang forever.

For example, add the above to zsh_profile and then try to build this repo: github.com/suborbital/subo using `make subo`

The install command will hang forever. If you remove the above and re-source the shell, it works fine.

Now I assume this is because the swiftenv shims are messing with the Go compiler backend.... and I also realize this isn't strictly within the scope of this project! That said, it's pretty unfortunate and hard to debug.

Is there anything that can be done to make this better? I'm happy to help in any way I can.

**Comment by kylef** [comment]
I wonder, does `env SWIFTENV_VERSION=system` allow`make subo` to complete? This should make the shims point to the system versions of the binary (i.e, invoking the clang shim runs system clang from `$PATH`).

Another thing you could do to help isolate the underlying cause is delete some of the shims and see which one causes it. They are all stored in `~/.swiftenv/shims`, note this includes many different shims, including`swift`, `clang` and `lldb` since Swift toolchains ship with their own clang and lldb. `rm ~/.swiftenv/shims/clang*` to delete clang shims for example.

`swiftenv rehash` will allow you to reset the shims back to their original state.
