### ISSUE TITLE
Not Loaded Error

### ISSUE THREAD

**Issue by wess** [kylef/swiftenv#19]
After installing swiftenv and dev version of Swift (with swiftenv). When i run `swift build --help` i get the following error: `dyld: Library not loaded: @rpath/libswiftCore.dylib`

Swift version: `swift-DEVELOPMENT-SNAPSHOT-2016-03-16-a`

**Comment by wess** [comment]
Full terminal details: http://wess.co/fUXr

**Comment by kylef** [comment]
This isn't actually a bug in swiftenv, it's a bug in the swift-build itself. The problem was already fixed in https://github.com/apple/swift-package-manager/pull/204 and there is a JIRA on Swift [SR-975](https://bugs.swift.org/browse/SR-975).

This bug was introduced in the `DEVELOPMENT-SNAPSHOT-2016-03-16-a` snapshot and will be resolved in the next snapshot.

**Comment by kylef** [comment]
Btw, the last snapshot `DEVELOPMENT-SNAPSHOT-2016-03-01-a` works.

```shell
$ swiftenv install DEVELOPMENT-SNAPSHOT-2016-03-01-a
```

**Comment by wess** [comment]
Thank you for the quick response!
