### ISSUE TITLE
Has promise, but kind of a pita to use currently.

### ISSUE THREAD

**Issue by crewshin** [kylef/swiftenv#24]
Context: nvm (Node Version Manager)

Things I miss:
- `nvm ls` (better than `swiftenv versions` by quite a bit imo). How about `svm ls`?
- `nvm ls-remote` displays a list of all available versions. <- amazingly helpful.
- `nvm install v4` will install the latest version of v4. eg. v4.4.9. As opposed to this craziness: swift-2.2.1-SNAPSHOT-2016-04-12-a

The last two in that list are pretty much deal breakers for me personally since I need to go the swift website to find the version I need to download anyway, just to pass into swiftenv. I'll just pull the file while I'm there and install it at that point.

**Comment by kylef** [comment]
There's a lot in here so let me try and answer this one by one.

> - `nvm ls` (better than `swiftenv versions` by quite a bit imo). How about `svm ls`?

What does `nvm ls` do and what would `svm ls` do?

> - `nvm ls-remote` displays a list of all available versions. <- amazingly helpful.

Isn't this just `swiftenv install --list`?

```shell
$ swiftenv install --list
2.2-dev
2.2
2.2.1
3.0-dev
```

> - `nvm install v4` will install the latest version of v4. eg. v4.4.9. As opposed to this craziness: swift-2.2.1-SNAPSHOT-2016-04-12-a

I disagree that installing a version by default should install a snapshot. It's still very early for Swift and we should prefer stable releases. I.e, `swiftenv install 2.2` should install `2.2`, not some snapshot version after `2.2`. The same with `2.2.1`.

As for implementing a way to get the latest snapshot, I can't see any easy way to do this since it changes every other week without adding substantial complexity to swiftenv. I think this is a rather short term problem and with stable releases for 2.2, 2.2.1 and in the future 3.0 users will be less likely to use these snapshots.

I also don't see a way that nvm supports automatic installing development releases such as [nodejs nightlies](https://nodejs.org/download/nightly/), which are the closest equivalent to Swift's snapshots.
