### ISSUE TITLE
Verify signatures against downloaded packages

### ISSUE THREAD

**Issue by robertjpayne** [kylef/swiftenv#64]
Swiftenv currently does not verify signatures from the downloaded tarballs. It would be great as a secondary peace of mind if it did.

**Comment by kylef** [comment]
Hi @robertjpayne,

I'm open to adding signature validation. However, I don't believe adding signature verification improves the security as you would imagine.

If we trust HTTPS enough to be able to safely download the signature from the swift.org server, I think we can trust the HTTPS connection to swift.org to download the actual binary of Swift.

If there were security concerns by downloading the binary from swift.org over https, then these same security concerns would apply to downloading the signature from the same source.

If it's possible for someone to alter the swift binary on swift.org, either as a man in the middle because of leaked TLS certificates or because they have direct access to the servers. They would also be able to tamper with the signature files. Therefore I don't see how this actually adds any security.

The binaries and signatures are hosted in the exact same source:

- `https://swift.org/builds/swift-3.0-release/ubuntu1510/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu15.10.tar.gz`
- `https://swift.org/builds/swift-3.0-release/ubuntu1510/swift-3.0-RELEASE/swift-3.0-RELEASE-ubuntu15.10.tar.gz.sig`

That said, signature validation has been on the back of my mind to add in the future, however this is pretty low in priority for me considering the other open tasks I have planned in swiftenv.

**Comment by robertjpayne** [comment]
@kylef The GPG key system is a public/private key pair. You install the public keys on your server and Apple signs the packages with a private key.

Assuming you don't automate the installation of the GPG keys an attacker could never spoof the signature against the public keys installed.

This would have to be optional as some environments it makes little sense (Continuous Integration etc…).

**Comment by kylef** [comment]
This is in now thanks to @stupergenius! Currently verification can be enabled with `--verify` during install, I'd like to add an environment variable to force it for all installs and to update the docker image and Travis CI helpers to verify by default next.

**Comment by kylef** [comment]
I've added `SWIFTENV_VERIFY` env variable (https://github.com/kylef/swiftenv/commit/d684c6abeda12aa92573c20a0ddad05a64ebaaf5), you can now set `export SWIFTENV_VERIFY=true` to force verification (unless you explicitly specify `--no-verify` to install).
