### ISSUE TITLE
Doesn't install 3.0 on Ubuntu 16.04

### ISSUE THREAD

**Issue by sauliusgrigaitis** [kylef/swiftenv#69]
I'm using `fac720df64c28bbc04832b65d245da72a2054be8` swiftenv.

```
$ swiftenv install --verbose 3.0
Checking for a URL for the 3.0 on ubuntu16.04.
Did not find a binary release for 3.0 on ubuntu16.04.
We don't have build instructions for 3.0.
```

**Comment by ianpartridge** [comment]
Confirmed

```bash
ubuntu@ubuntu-xenial:~$ swiftenv install --list
2.2-dev
2.2
2.2.1
3.0-dev
ubuntu@ubuntu-xenial:~$ swiftenv install 3.0
We don't have build instructions for 3.0.
```

**Comment by aitbw** [comment]
Can confirm this also occurs under Manjaro Linux 16.06.

**Comment by kylef** [comment]
Currently swiftenv only has a binary installation instructions for Swift 3.0 and not build instructions for Swift 3.0. That means when building from source or on a platform that Apple doesn't provide a binary for. You will get an error because these instructions are not yet created.

I've been trying to create and test a build profile for Swift 3.0, but it's providing time consuming due to Swift the time it takes to build Swift. I need to test it on multiple platforms to ensure the instructions work in all environments. Given my current low powered systems this is a very time consuming operation.

The following is what I have so far, you should be able to place it inside `share/swiftenv-build/3.0` inside your swiftenv install.

```bash
TAG="swift-3.0-RELEASE"
fetch_git swift "$TAG" swift
./swift/utils/update-checkout --clone --branch "$TAG"
build_swift
```

This will allow you to build Swift 3.0 from source, there may be problems with it. I have not been able to fully test it.

---

If you want like to force using a binary for a different similar platform, this may work. You may be able to install Swift binaries for similar versions of Ubuntu.

Example:

```shell
$ env PLATFORM=ubuntu15.10 swiftenv install 3.0
```

**Comment by s1ddok** [comment]
bump the issue, can't use this on Ubuntu 14.04. Installation in binary form might work as well for most users I think!

**Comment by stupergenius** [comment]
@s1ddok Can you open a separate issue with repro steps please, and your expected behavior?
